version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: banko1234
      MYSQL_DATABASE: project_tracker
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: node
      MONGO_INITDB_ROOT_PASSWORD: banko1234
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: project_tracker_app
    depends_on:
      - mysql
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: banko1234
      SPRING_DATA_MONGODB_URI: mongodb://node:banko1234@mongo:27017/test?authSource=admin
    networks:
      - backend

volumes:
  mysql_data:
  mongo_data:

networks:
  backend:
