version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/project_tracker?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/project_tracker
    depends_on:
      - mysql-db
      - mongodb
    networks:
      - backend-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=project_tracker
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=project_tracker
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-network

volumes:
  mysql-data:
  mongo-data:

networks:
  backend-network:
    driver: bridge